/*
  GENERATED by scripts/gen-video-meta.mjs — do not edit by hand.
  Run `npm run video:meta` to refresh after changing any clip.

  uploadDate is the date the file was first committed, so VideoObject carries a
  real publication date rather than an invented one.
*/
export type VideoMeta = {
  uploadDate: string
  duration: string
  seconds: number
  width: number
  height: number
}

export const videoMeta: Record<string, VideoMeta> = {
  '/work/ai-orchestra.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1880, height: 910 },
  '/work/ai-trading-terminal.mp4': { uploadDate: '2026-08-11', duration: 'PT12S', seconds: 12, width: 1280, height: 638 },
  '/work/aura.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1562, height: 900 },
  '/work/auren.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1912, height: 940 },
  '/work/axiom.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1558, height: 908 },
  '/work/factory-os.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1904, height: 940 },
  '/work/geoiq.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1280, height: 642 },
  '/work/l1.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1880, height: 904 },
  '/work/orchestr.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1862, height: 932 },
  '/work/p2p.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1864, height: 900 },
  '/work/predikt.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1576, height: 872 },
  '/work/quantos.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1904, height: 934 },
  '/work/quat-ai.mp4': { uploadDate: '2026-08-11', duration: 'PT12S', seconds: 12, width: 1280, height: 624 },
  '/work/terminal.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1920, height: 936 },
  '/work/vivid.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1602, height: 904 },
  '/work/yap.mp4': { uploadDate: '2026-08-02', duration: 'PT12S', seconds: 12, width: 1582, height: 888 },
}
